DROP TABLE IF EXISTS person;

CREATE TABLE person(
    person_id int GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
	person_name varchar(50)not null,
	person_age int not null,
	person_email varchar(100)not null
);
INSERT INTO person(person_name,person_age,person_email)VALUES(
    'Timur',21,'taddevan@gmail.com'
);
INSERT INTO person(person_name,person_age,person_email)VALUES(
    'Toha',51,'erdevan@gmail.com'
);
INSERT INTO person(person_name,person_age,person_email)VALUES(
    'Akbur',6,'uddevan@gmail.com'
);